/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
/* Header for class com_example_matthew_gesturerecognitionapplication_OpenCV */

using namespace cv;
#ifndef _Included_com_example_matthew_gesturerecognitionapplication_OpenCV
#define _Included_com_example_matthew_gesturerecognitionapplication_OpenCV
#ifdef __cplusplus
extern "C" {
#endif
void detect(Mat& frame);


JNIEXPORT void JNICALL Java_com_example_matthew_gesturerecognitionapplication_OpenCV_faceDetection
(JNIEnv *, jclass, jlong);
#ifdef __cplusplus
}
#endif
#endif
